idf_component_register(
    SRCS 
        "main.c"
        "globals.c"
        "orientation.c"
        "beep.c"
        "sensor_manager.c"
        "sensor_filtering.c"
        "lora_interface.c"
        "flash_interface.c"
        "flight.c"
        "sensor_fusion.c"
        "serial_util.c"
        "sitl.c"
        "goober.c"
        "sensor/orientation.c"
        "sensor/sensor_manager.c"
        "sensor/sensor_filtering.c"
        "move-to-drivers/lora_interface.c"
        "move-to-drivers/flash_interface.c"
        "fsm/flight.c"
        "sensor/sensor_fusion.c"
        "sitl/serial_util.c"
        "sitl/sitl.c"
    INCLUDE_DIRS 
        "sitl"
        "fsm"
        "move-to-drivers"
        "sensor"
        "${CMAKE_CURRENT_SOURCE_DIR}/../"
)