idf_component_register(
    SRCS 
        "main.c"
        "globals.c"
        "radio/goober.c"
        "sensor/orientation.c"
        "sensor/sensor_manager.c"
        "sensor/sensor_filtering.c"
        "radio/lora_interface.c"
        "memory/flash_interface.c"
        "memory/nvs_interface.c"
        "fsm/flight.c"
        "sensor/sensor_fusion.c"
        "sitl/serial_util.c"
        "sitl/sitl.c"
    INCLUDE_DIRS 
        "sitl"
        "fsm"
        "radio"
        "memory"
        "sensor"
        "${CMAKE_CURRENT_SOURCE_DIR}/../"
    REQUIRES esp_timer
)